name: kg-chat QC

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8", "3.11" ]

    steps:
      - uses: actions/checkout@v3.0.2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.1
      - name: Install dependencies
        run: poetry install --no-interaction

#      - name: Check common spelling errors
#        run: poetry run tox -e codespell

      - name: Check code quality
        run: poetry run tox -e lint

      - name: Test with pytest
        env:
          SKIP_NEO4J_TESTS: true
          SKIP_DUCKDB_TESTS: true
          OPENAI_API_KEY: "mock_key"
        run: poetry run pytest
